
prompt off 2> /dev/null

autoload -Uz vcs_info
precmd() {
    printf "\033]133;A\007"
    vcs_info
}
zstyle ':vcs_info:git:*' formats '%b '

setopt PROMPT_SUBST

ERR_CODE='%B%F{red}%(?..%? )%f%b'
GIT_FMT='%F{green}${vcs_info_msg_0_}%f'
PROMPT_ICON_FMT='%B%F{blue}$ %f%b'
PROMPT="$ERR_CODE$GIT_FMT%T $PROMPT_ICON_FMT"
